

const FAQ = () => {
  return (
    <section className="py-24 px-8">
      <div className="max-w-3xl mx-auto">
        <h2 className="text-4xl font-headline font-black mb-12 text-center">Frequently Asked</h2>
        <div className="space-y-4">
          <details className="group bg-surface-container-low p-6 rounded-lg transition-all" open>
            <summary className="flex justify-between items-center cursor-pointer list-none">
              <h4 className="font-headline font-bold">What is Arbitrum Sepolia?</h4>
              <span className="material-symbols-outlined transition-transform group-open:rotate-180" data-icon="expand_more">expand_more</span>
            </summary>
            <p className="mt-4 text-on-surface-variant text-sm">It is the primary testnet for Arbitrum, allowing users to test VerdexSwap features with zero real financial risk while enjoying Ethereum-level security.</p>
          </details>
          <details className="group bg-surface-container-low p-6 rounded-lg transition-all">
            <summary className="flex justify-between items-center cursor-pointer list-none">
              <h4 className="font-headline font-bold">How is the IL Shield funded?</h4>
              <span className="material-symbols-outlined transition-transform group-open:rotate-180" data-icon="expand_more">expand_more</span>
            </summary>
            <p className="mt-4 text-on-surface-variant text-sm">It's funded by a 0.05% fee on every trade and the interest generated by the IL Vault assets.</p>
          </details>
          <details className="group bg-surface-container-low p-6 rounded-lg transition-all">
            <summary className="flex justify-between items-center cursor-pointer list-none">
              <h4 className="font-headline font-bold">Can I lose money in the IL Vault?</h4>
              <span className="material-symbols-outlined transition-transform group-open:rotate-180" data-icon="expand_more">expand_more</span>
            </summary>
            <p className="mt-4 text-on-surface-variant text-sm">While the vault is designed for stability, in extreme market events where payouts exceed the buffer, vault capital may be used to cover the shortfall.</p>
          </details>
        </div>
      </div>
    </section>
  );
};

export default FAQ;
