const IlVaultStaking = () => (
  <section className="py-24 px-8">
    <div className="max-w-7xl mx-auto glass-panel p-12 rounded-2xl border-primary-container/30 relative overflow-hidden">
      <div className="absolute top-0 right-0 w-64 h-64 bg-primary-container/5 rounded-full -translate-y-1/2 translate-x-1/2 blur-3xl" />
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
        <div>
          <h2 className="text-4xl font-headline font-black mb-6">Earn yield by underwriting the insurance.</h2>
          <p className="text-on-surface-variant mb-6 text-lg">The IL Vault needs USDC liquidity to pay out IL claims. Stakers provide that liquidity and earn a share of all fee conversions in return. It's a real yield — generated by real trading activity.</p>
          <p className="text-on-surface-variant mb-10 text-sm">APY depends on protocol volume and vault utilization. We don't publish projected numbers — check the live Earn page for current rates derived from on-chain data.</p>
          <div className="space-y-4">
            {[
              'Yield paid in USDC — no volatile token exposure',
              'Cooldown period protects LP coverage stability',
              'Circuit breaker prevents vault over-utilization',
              'Fee share configurable by governance over time',
            ].map(item => (
              <div key={item} className="flex items-start gap-4">
                <span className="bg-primary-container p-2 rounded-full text-on-primary flex-shrink-0">
                  <span className="material-symbols-outlined text-sm">check</span>
                </span>
                <span className="text-sm">{item}</span>
              </div>
            ))}
          </div>
        </div>
        <div className="bg-surface-container-lowest p-8 rounded-xl border border-outline-variant/40">
          <div className="mb-6 p-4 bg-primary-container/5 border border-primary-container/20 rounded-lg">
            <p className="text-sm text-primary-container font-bold mb-1">Live on Arbitrum Sepolia</p>
            <p className="text-xs text-on-surface-variant">Vault is deployed and accepting USDC. APY reflects real fee conversions from actual trading activity.</p>
          </div>
          <div className="p-4 bg-error-container/20 border border-error/30 rounded mb-6">
            <div className="flex gap-3 items-center text-error">
              <span className="material-symbols-outlined">info</span>
              <span className="text-sm font-bold">Unstake Cooldown Required</span>
            </div>
            <p className="text-xs mt-2 text-on-surface-variant">Withdrawals require requesting unstake first. The cooldown period is set by the vault config and ensures LP coverage remains stable during high-utilization periods.</p>
          </div>
          <a href="/earn" className="block w-full py-4 text-center bg-primary text-on-primary font-bold rounded-md hover:bg-primary-container transition-all">Go to Vault</a>
        </div>
      </div>
    </div>
  </section>
);

export default IlVaultStaking;
